### ISSUE TITLE
Divs inside of list items

### ISSUE THREAD

**Issue by calebeby** [jgm/djoths#10]
```
1. Hello
   
   ::: hi
   inside list?
   :::

   ::: hi
   inside list?
   :::
```

The JS implementation provides the result I expect (divs inside of list item):

https://djot.net/playground/?text=1.+Hello%0A+++%0A+++%3A%3A%3A+hi%0A+++inside+list%3F%0A+++%3A%3A%3A%0A%0A+++%3A%3A%3A+hi%0A+++inside+list%3F%0A+++%3A%3A%3A&sourcepos=false

The haskell implementation does not (the second div makes the list end):

`pandoc -i foo.dj -t html`

```
<ol class="incremental" type="1">
<li><p>Hello</p>
<div class="hi" data-wrapper="1">

</div></li>
</ol>
<div class="hi" data-wrapper="1">

</div>
```

A workaround is removing the empty line between the divs. Paragraphs and divs together in list items, or divs in list items followed by other list items, seem to be problematic also.

**Comment by jgm** [comment]
Thanks!

**Comment by jgm** [comment]
The wrapper="1" is also wrong on those divs, but that needs fixing elsewhere.
