### ISSUE TITLE
djot list occluding following blocks

### ISSUE THREAD

**Issue by ghost** [jgm/djoths#4]
**Explain the problem.**
I was recently compelled to experiment with both [pandoc](https://github.com/jgm/pandoc) and [djot](https://github.com/jgm/djot). Truthfully I know very little about both and even less about Haskell. I understand that djot is early in both definition and development, and I apologize if I'm poking at an understood issue. Anyway, after reading through the available syntax guidelines for djot, I attempted converting a file, `text.djot` to HTML.

`text.djot`
```
1. one
2. two
3. three

four
five
six

seven
eight
nine
```
With the above input, I ran pandoc and got the following output:

```
user@computer:/tmp/djot$ pandoc text.djot -f djot -t html
<ol type="1">
<li>one</li>
<li>two</li>
<li>three</li>
</ol>
```

Unexpectedly, pandoc omitted everything after the first list. Funnily enough, altering `text.djot` to include an attribute removes the occlusion of all following blocks.
`text.djot`
```
1. one
2. two
3. three

four
five
six

{}
seven
eight
nine
```
Instead I recieved the following ouput:
```
user@computer:/tmp/djot$ pandoc text.djot -f djot -t html
<ol type="1">
<li>one</li>
<li>two</li>
<li>three</li>
</ol>
<p>seven eight nine</p>
```

After reading the djot syntax guidelines and experimenting with the [djot playground](https://djot.net/playground) I'm assuming this is not expected behavior. 

**Pandoc version?**
I built and installed `pandoc 3.1.12.2` according to the `Quick cabal method` shown at [the installation document](https://github.com/jgm/pandoc/blob/main/INSTALL.md#quick-cabal-method).

I am running an `amd64-debian-12` system.

```
user@computer:/tmp/djot$ pandoc --version
pandoc 3.1.12.2
Features: +server +lua
Scripting engine: Lua 5.4
...
```

**Comment by jgm** [comment]
Definitely a bug! Moving to djoths.

**Comment by ghost** [comment]
I've had some time to compile your patch and test and found that it still doesn't behave quite as expected.

Given
`text.djot`
```
1. one
2. two
3. three

|four|five|six|

seven
eight
nine
```
the output is as follows
```
user@computer:/tmp/djot$ pandoc text.djot -f djot -t html
<ol type="1">
<li>one</li>
<li>two</li>
<li>three</li>
</ol>
<p>|four|five|six|</p>
<p>seven eight nine</p>
```
as opposed to the expected
```
user@computer:/tmp/djot$ pandoc text.djot -f djot -t html
<ol type="1">
<li>one</li>
<li>two</li>
<li>three</li>
</ol>
<table>
<tbody>
<tr class="odd">
<td><p>four</p></td>
<td><p>five</p></td>
<td><p>six</p></td>
</tr>
</tbody>
</table>
<p>seven eight nine</p>
```

Once again adding an attribute before the block solves the problem and gives the expected output:
`text.djot`
```
1. one
2. two
3. three

{}
|four|five|six|

seven
eight
nine
```
```
user@computer:/tmp/djot$ pandoc text.djot -f djot -t html
<ol type="1">
<li>one</li>
<li>two</li>
<li>three</li>
</ol>
<table>
<tbody>
<tr class="odd">
<td><p>four</p></td>
<td><p>five</p></td>
<td><p>six</p></td>
</tr>
</tbody>
</table>
<p>seven eight nine</p>
```

An additional problem is revealed when attempting to write two separate consecutive tables:
`text.djot`
```
|one|two|three|

|four|five|six|
```
```
user@computer:/tmp/djot$ pandoc text.djot -f djot -t html
<table>
<tbody>
<tr class="odd">
<td><p>one</p></td>
<td><p>two</p></td>
<td><p>three</p></td>
</tr>
<tr class="even">
<td><p>four</p></td>
<td><p>five</p></td>
<td><p>six</p></td>
</tr>
</tbody>
</table
```

Identically, two consecutive tight lists results in a single loose list:
`text.djot`
```
1. one
2. two
3. three


4. four
5. five
6. six
```
```
<ol type="1">
<li><p>one</p></li>
<li><p>two</p></li>
<li><p>three</p></li>
<li><p>four</p></li>
<li><p>five</p></li>
<li><p>six</p></li>
</ol>
```

This behavior for tables is opposite to that of the djot playground while identical for lists. Although this is the case, this would make it impossible to have two consecutive lists without first attaching an attribute to the bottom list.

Is it possible to allow separating these different blocks?

**Comment by jgm** [comment]
Thanks: re-opening.  I think all of these issues may be due to a misguided performance optimization I added a while back.

**Comment by jgm** [comment]
The final example (two list) behavior is not really a bug in this implementation.  We could rethink djot's behavior on this.  But that should be raised either in issues or discussion on jgm/djot.
