### ISSUE TITLE
Tables in lists are parsed incorrectly (pandoc user)

### ISSUE THREAD

**Issue by calebeby** [jgm/djoths#8]
Hi! I don't use the haskell library directly, instead just through pandoc. Feel free to move this issue to the pandoc repo if it is more relevant there!

Here is some test code:

```
1. Complete the table.

    | Month    | Number of Employees |
    |:--------:|:-------------------:|
    | Month 1  |                     |
    | Month 2  |                     |
    | Month 3  |                     |
    | Month 4  |                     |
    | Month 6  |                     |
    | Month 11 |                     |
```

In the JS implementation on https://djot.net/playground/, it parses correctly (a table inside a list item).

In the haskell implementation it parses as a bunch of single-row tables inside the list item: 
![image](https://github.com/user-attachments/assets/b26fb6d3-7e56-4b23-83e1-9b8c8b84b91f)

Thank you for making the wonderful world of pandoc! It has been a central tool in my teaching :)

**Comment by jgm** [comment]
Thanks.  I think the problem has to do with indentation and is not specific to a list item.
```
 | test | test |
 |------|------|
 | 1    | 2    |
```
yields
```html
<table>
<tbody>
<tr>
<td><p>test</p></td>
<td><p>test</p></td>
</tr>
</tbody>
</table>
<table>

</table>
<table>
<tbody>
<tr>
<td><p>1</p></td>
<td><p>2</p></td>
</tr>
</tbody>
</table>
```
but if you leave off that 1-space indent you get a single table.

**Comment by calebeby** [comment]
I am not sure if this is what you are saying, but I also tried these versions with less indentation with the same result:


```
1. Complete the table.

   | Month    | Number of Employees |
   |:--------:|:-------------------:|
   | Month 1  |                     |
   | Month 2  |                     |
   | Month 3  |                     |
   | Month 4  |                     |
   | Month 6  |                     |
   | Month 11 |                     |
```

```
1. Complete the table.

  | Month    | Number of Employees |
  |:--------:|:-------------------:|
  | Month 1  |                     |
  | Month 2  |                     |
  | Month 3  |                     |
  | Month 4  |                     |
  | Month 6  |                     |
  | Month 11 |                     |
```

Does the list item parser not take up the whitespace from stuff indented inside of it?
